Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,38 +1,62 @@
 #!/bin/bash
 
-# Обновление и установка базовых пакетов
+termux-setup-storage
+
+read -p "Do you want to proceed with the installation? (y/N) " -n 1 -r
+echo
+if [[ $REPLY != "y" && $REPLY != "Y" ]]; then
+    echo "Installation aborted."
+    exit 1
+fi
+
+echo "Updating packages..."
 pkg update -y
+pkg upgrade -y
+
+echo "Installing packages..."
 pkg install x11-repo -y
-pkg install termux-x11-nightly -y
 pkg install pulseaudio -y
+pkg install xwayland -y
 pkg install wget -y
-# Установка XFCE4 окружения
+pkg install tsu -y
+pkg install root-repo -y
+pkg install patchelf -y
+pkg install p7zip -y
+pkg install xorg-xrandr -y
+pkg install ncurses-utils -y
+pkg install hashdeep -y
+pkg install git -y
+pkg install tar -y
+pkg install glibc-repo -y
+pkg install mesa -y
 pkg install xfce4 -y
+pkg install mesa-zink -y
+pkg install virglrenderer-mesa-zink -y
+pkg install vulkan-loader-android -y
+pkg install virglrenderer-android -y
+pkg install android-tools -y
+pkg install python-tkinter -y
+pkg install xfce4-whiskermenu-plugin -y
+pkg install xfce4-screenshooter -y
+pkg install xfce4-taskmanager -y
+pkg install xfce4-docklike-plugin -y
+pkg install matchbox-keyboard -y
 
-# Установка Chromium (опционально)
-pkg install tur-repo
-pkg install chromium
-
-# Установка VS Code (опционально)
-pkg install code-oss
-
-# Скачивание скрипта запуска XFCE4
-wget https://raw.githubusercontent.com/LinuxDroidMaster/Termux-Desktops/main/scripts/termux_native/startxfce4_termux.sh
-chmod +x startxfce4_termux.sh
-
-# Скачивание и установка Mobox launcher скрипта
-cd ~
-wget https://raw.githubusercontent.com/LinuxDroidMaster/Termux-Desktops/main/scripts/termux_native/mobox_run.sh
-mv mobox_run.sh boxwine
-chmod +x boxwine
-
-# Скачивание ярлыка для рабочего стола
+echo "Setting up Desktop folder and downloading shortcuts..."
 mkdir -p ~/Desktop
 cd ~/Desktop
-wget https://raw.githubusercontent.com/LinuxDroidMaster/Termux-Desktops/main/scripts/termux_native/MoboxExplorer.desktop
-cd ~
 
-echo
-echo "Установка завершена!"
-echo "Запуск XFCE4: ./startxfce4_termux.sh"
-echo "Запуск Wine Explorer: ./boxwine explorer"
+wget -O "wine explorer.desktop" "https://raw.githubusercontent.com/shephard-dev/Emulator/main/apps/wine%20explorer.desktop"
+wget -O "task manager.desktop" "https://raw.githubusercontent.com/shephard-dev/Emulator/main/apps/task%20manager.desktop"
+
+echo "Downloading and extracting glibc..."
+cd "$PREFIX"
+
+wget -O glibc.tar.xz "https://github.com/shephard-dev/Emulator/releases/download/Files/glibc.tar.xz"
+tar -xf glibc.tar.xz
+rm glibc.tar.xz
+
+chmod +x "$PREFIX/glibc/opt/scripts/yebanos"
+ln -sf "$PREFIX/glibc/opt/scripts/yebanos" "$PREFIX/bin/yebanos"
+
+echo "Installation complete! Type 'yebanos' to start."
